name: Production test and build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      matrix:
        service:
          - bigquery-outbound
          - ble-inbound
          - chromecast-logic-pool
          - data-panel-api
          - data-panel-front
          - device-controller
          - dns-updater
          - hue-inbound
          - hue-logic-pool
          - hue-outbound
          - hue-sensors-alerts
          - ikea-inbound
          - ikea-outbound
          - logger
          - logic-pool
          - timer
          - monitor-heartbeat-control
          - monitor-heartbeat-request
          - monitor-http-request
          - notification-message
          - notification-voice
          - task-scheduler
          - telegram-bot
    uses: ./.github/workflows/build-service.yml
    with:
      service: ${{ matrix.service }}
      tag: main
    secrets:
      REGISTRY: ${{secrets.REGISTRY}}
      REGISTRY_REPO: ${{secrets.REGISTRY_REPO}}
      GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

  deploy:
    name: Deploy to production environment
    runs-on: ubuntu-latest
    needs: 
      - build
    if: ${{ always() && !failure() && !cancelled() }}
    steps:
      - name: Request update
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DIP_URL }}
          method: "POST"
          bearerToken: ${{ secrets.DIP_TOKEN }}